//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class DelegacionMunicipal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DelegacionMunicipal()
        {
            this.Reportes = new ObservableCollection<Reporte>();
            this.Usuarios = new ObservableCollection<Usuario>();
        }
    
        public int idDelegacion { get; set; }
        public string nombre { get; set; }
        public int numero { get; set; }
        public string colonia { get; set; }
        public string calle { get; set; }
        public int codigoPostal { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string municipio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Reporte> Reportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Usuario> Usuarios { get; set; }
    }
}
