//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Reporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reporte()
        {
            this.Vehiculoes = new ObservableCollection<Vehiculo>();
        }
    
        public int idReporte { get; set; }
        public string calle { get; set; }
        public string colonia { get; set; }
        public byte[] fotografia { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public string estatus { get; set; }
    
        public virtual DelegacionesMunicipale DelegacionesMunicipale { get; set; }
        public virtual Dictaman Dictaman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Vehiculo> Vehiculoes { get; set; }
    }
}
