//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Reportes = new ObservableCollection<Reporte>();
        }
    
        public int idVehiculo { get; set; }
        public string numeroPolizaSeguro { get; set; }
        public string nombreAseguradora { get; set; }
        public string color { get; set; }
        public int año { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public string numeroPlaca { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Reporte> Reportes { get; set; }
    }
}
